name: Run Python Script 4

on:
  schedule:
    - cron: '0 */2 * * *'
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repo
      - name: Checkout repo
        uses: actions/checkout@v3

      # 2. Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      # 3. Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4. Download previous posted_urls.txt (if any)
      - name: Download previous posted_urls.txt
        uses: actions/download-artifact@v3
        with:
          name: posted-urls
          path: .

      # 5. Run Python script
      - name: Run script
        env:
          REDDIT_CLIENT_ID: ${{ secrets.REDDIT_CLIENT_ID }}
          REDDIT_CLIENT_SECRET: ${{ secrets.REDDIT_CLIENT_SECRET }}
          MASTODON_ACCESS_TOKEN: ${{ secrets.MASTODON_ACCESS_TOKEN }}
          MASTODON_API_BASE_URL: ${{ secrets.MASTODON_API_BASE_URL }}
        run: python positive.py

      # 6. Upload posted_urls.txt to persist across runs
      - name: Upload posted_urls.txt
        uses: actions/upload-artifact@v3
        with:
          name: posted-urls
          path: posted_urls.txt
